export const galleryPictures = [
    {title: 'ar-1.jpeg'},
    {title: 'a12-1.jpg'},
    {title: 'a11.jpg'},
    {title: 'a7.jpeg'},
    {title: 'a8.jpeg'},
    {title: 'ar-3.jpeg'},
    {title: 'ar-6.jpeg'},
    {title: 'aryan-18.jpg'},
    {title: 'aryan-22.jpg'},
    {title: 'aryan-23.jpg'},
    {title: 'a10.jpeg'},
    {title: 'a9.jpeg'},
    {title: 'a13.jpeg'},
    {title: 'aryan-24.jpg'},
    {title: 'ar-2.jpeg'},
    {title: 'ar-4.jpeg'},
    {title: 'ar-5.jpeg'},
    {title: 'ar-7.jpeg'},
    {title: 'ar-8.jpeg'},
    {title: 'ar-9.jpeg'},
]